/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.Entities;


import SS.DesktopApp.Domain.tables.Cliente;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClienteRecord extends UpdatableRecordImpl<ClienteRecord> implements Record13<Integer, String, String, String, String, String, String, Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 1706621965;

    /**
     * Setter for <code>ADMIN.CLIENTE.ID_CUS</code>.
     */
    public void setIdCus(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.ID_CUS</code>.
     */
    public Integer getIdCus() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.RFC</code>.
     */
    public void setRfc(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.RFC</code>.
     */
    public String getRfc() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.FIRSTNAME</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.FIRSTNAME</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.LASTNAME</code>.
     */
    public void setLastname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.LASTNAME</code>.
     */
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.CALLE</code>.
     */
    public void setCalle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.CALLE</code>.
     */
    public String getCalle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.NUMERO</code>.
     */
    public void setNumero(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.NUMERO</code>.
     */
    public String getNumero() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.COLONIA</code>.
     */
    public void setColonia(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.COLONIA</code>.
     */
    public String getColonia() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.CP</code>.
     */
    public void setCp(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.CP</code>.
     */
    public Integer getCp() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.CIUDAD</code>.
     */
    public void setCiudad(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.CIUDAD</code>.
     */
    public String getCiudad() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.ESTADO</code>.
     */
    public void setEstado(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.ESTADO</code>.
     */
    public String getEstado() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.TEL_CELULAR</code>.
     */
    public void setTelCelular(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.TEL_CELULAR</code>.
     */
    public String getTelCelular() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ADMIN.CLIENTE.TEL_EMPRESA</code>.
     */
    public void setTelEmpresa(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>ADMIN.CLIENTE.TEL_EMPRESA</code>.
     */
    public String getTelEmpresa() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, Integer, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, Integer, String, String, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cliente.CLIENTE.ID_CUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cliente.CLIENTE.RFC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Cliente.CLIENTE.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Cliente.CLIENTE.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Cliente.CLIENTE.CALLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Cliente.CLIENTE.NUMERO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Cliente.CLIENTE.COLONIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Cliente.CLIENTE.CP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Cliente.CLIENTE.CIUDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Cliente.CLIENTE.ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Cliente.CLIENTE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Cliente.CLIENTE.TEL_CELULAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Cliente.CLIENTE.TEL_EMPRESA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdCus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRfc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCalle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNumero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getColonia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getCp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTelCelular();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getTelEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdCus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRfc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCalle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNumero();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getColonia();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTelCelular();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTelEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value1(Integer value) {
        setIdCus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value2(String value) {
        setRfc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value4(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value5(String value) {
        setCalle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value6(String value) {
        setNumero(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value7(String value) {
        setColonia(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value8(Integer value) {
        setCp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value9(String value) {
        setCiudad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value10(String value) {
        setEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value11(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value12(String value) {
        setTelCelular(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord value13(String value) {
        setTelEmpresa(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClienteRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, String value9, String value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClienteRecord
     */
    public ClienteRecord() {
        super(Cliente.CLIENTE);
    }

    /**
     * Create a detached, initialised ClienteRecord
     */
    public ClienteRecord(Integer idCus, String rfc, String firstname, String lastname, String calle, String numero, String colonia, Integer cp, String ciudad, String estado, String email, String telCelular, String telEmpresa) {
        super(Cliente.CLIENTE);

        set(0, idCus);
        set(1, rfc);
        set(2, firstname);
        set(3, lastname);
        set(4, calle);
        set(5, numero);
        set(6, colonia);
        set(7, cp);
        set(8, ciudad);
        set(9, estado);
        set(10, email);
        set(11, telCelular);
        set(12, telEmpresa);
    }
}
