/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.Entities;


import SS.DesktopApp.Domain.tables.Producto;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductoRecord extends UpdatableRecordImpl<ProductoRecord> implements Record10<String, String, String, Integer, Double, Double, Double, Boolean, Integer, Integer> {

    private static final long serialVersionUID = 1662783390;

    /**
     * Setter for <code>ADMIN.PRODUCTO.CLAVE</code>.
     */
    public void setClave(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.CLAVE</code>.
     */
    public String getClave() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.NOMBRE</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.NOMBRE</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.CLAVESAT</code>.
     */
    public void setClavesat(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.CLAVESAT</code>.
     */
    public String getClavesat() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.PAQUETE</code>.
     */
    public void setPaquete(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.PAQUETE</code>.
     */
    public Integer getPaquete() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.COSTO</code>.
     */
    public void setCosto(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.COSTO</code>.
     */
    public Double getCosto() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.PRECIO1</code>.
     */
    public void setPrecio1(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.PRECIO1</code>.
     */
    public Double getPrecio1() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.PRECIO2</code>.
     */
    public void setPrecio2(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.PRECIO2</code>.
     */
    public Double getPrecio2() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.INVENTARIO</code>.
     */
    public void setInventario(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.INVENTARIO</code>.
     */
    public Boolean getInventario() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.MINIMO</code>.
     */
    public void setMinimo(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.MINIMO</code>.
     */
    public Integer getMinimo() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>ADMIN.PRODUCTO.ACTUAL</code>.
     */
    public void setActual(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>ADMIN.PRODUCTO.ACTUAL</code>.
     */
    public Integer getActual() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Integer, Double, Double, Double, Boolean, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, Integer, Double, Double, Double, Boolean, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Producto.PRODUCTO.CLAVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Producto.PRODUCTO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Producto.PRODUCTO.CLAVESAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Producto.PRODUCTO.PAQUETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Producto.PRODUCTO.COSTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Producto.PRODUCTO.PRECIO1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Producto.PRODUCTO.PRECIO2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Producto.PRODUCTO.INVENTARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Producto.PRODUCTO.MINIMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Producto.PRODUCTO.ACTUAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getClave();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getClavesat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPaquete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getCosto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getPrecio1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getPrecio2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getInventario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getMinimo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getActual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getClave();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getClavesat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPaquete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getCosto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getPrecio1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getPrecio2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getInventario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getMinimo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getActual();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value1(String value) {
        setClave(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value2(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value3(String value) {
        setClavesat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value4(Integer value) {
        setPaquete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value5(Double value) {
        setCosto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value6(Double value) {
        setPrecio1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value7(Double value) {
        setPrecio2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value8(Boolean value) {
        setInventario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value9(Integer value) {
        setMinimo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord value10(Integer value) {
        setActual(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductoRecord values(String value1, String value2, String value3, Integer value4, Double value5, Double value6, Double value7, Boolean value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductoRecord
     */
    public ProductoRecord() {
        super(Producto.PRODUCTO);
    }

    /**
     * Create a detached, initialised ProductoRecord
     */
    public ProductoRecord(String clave, String nombre, String clavesat, Integer paquete, Double costo, Double precio1, Double precio2, Boolean inventario, Integer minimo, Integer actual) {
        super(Producto.PRODUCTO);

        set(0, clave);
        set(1, nombre);
        set(2, clavesat);
        set(3, paquete);
        set(4, costo);
        set(5, precio1);
        set(6, precio2);
        set(7, inventario);
        set(8, minimo);
        set(9, actual);
    }
}
