/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.Entities;


import SS.DesktopApp.Domain.tables.RenglonFactura;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RenglonFacturaRecord extends TableRecordImpl<RenglonFacturaRecord> implements Record6<Integer, String, Double, Integer, Integer, Double> {

    private static final long serialVersionUID = -5612024;

    /**
     * Setter for <code>ADMIN.RENGLON_FACTURA.FACTURA</code>.
     */
    public void setFactura(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ADMIN.RENGLON_FACTURA.FACTURA</code>.
     */
    public Integer getFactura() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ADMIN.RENGLON_FACTURA.ID_PROD</code>.
     */
    public void setIdProd(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ADMIN.RENGLON_FACTURA.ID_PROD</code>.
     */
    public String getIdProd() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ADMIN.RENGLON_FACTURA.PRECIO</code>.
     */
    public void setPrecio(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>ADMIN.RENGLON_FACTURA.PRECIO</code>.
     */
    public Double getPrecio() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>ADMIN.RENGLON_FACTURA.CANTIDAD</code>.
     */
    public void setCantidad(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ADMIN.RENGLON_FACTURA.CANTIDAD</code>.
     */
    public Integer getCantidad() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ADMIN.RENGLON_FACTURA.LISTA</code>.
     */
    public void setLista(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ADMIN.RENGLON_FACTURA.LISTA</code>.
     */
    public Integer getLista() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ADMIN.RENGLON_FACTURA.SUBTOTAL</code>.
     */
    public void setSubtotal(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>ADMIN.RENGLON_FACTURA.SUBTOTAL</code>.
     */
    public Double getSubtotal() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Double, Integer, Integer, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Double, Integer, Integer, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RenglonFactura.RENGLON_FACTURA.FACTURA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RenglonFactura.RENGLON_FACTURA.ID_PROD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return RenglonFactura.RENGLON_FACTURA.PRECIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RenglonFactura.RENGLON_FACTURA.CANTIDAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return RenglonFactura.RENGLON_FACTURA.LISTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return RenglonFactura.RENGLON_FACTURA.SUBTOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFactura();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getIdProd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getLista();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFactura();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIdProd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLista();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFacturaRecord value1(Integer value) {
        setFactura(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFacturaRecord value2(String value) {
        setIdProd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFacturaRecord value3(Double value) {
        setPrecio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFacturaRecord value4(Integer value) {
        setCantidad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFacturaRecord value5(Integer value) {
        setLista(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFacturaRecord value6(Double value) {
        setSubtotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFacturaRecord values(Integer value1, String value2, Double value3, Integer value4, Integer value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RenglonFacturaRecord
     */
    public RenglonFacturaRecord() {
        super(RenglonFactura.RENGLON_FACTURA);
    }

    /**
     * Create a detached, initialised RenglonFacturaRecord
     */
    public RenglonFacturaRecord(Integer factura, String idProd, Double precio, Integer cantidad, Integer lista, Double subtotal) {
        super(RenglonFactura.RENGLON_FACTURA);

        set(0, factura);
        set(1, idProd);
        set(2, precio);
        set(3, cantidad);
        set(4, lista);
        set(5, subtotal);
    }
}
