/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.Entities;


import SS.DesktopApp.Domain.tables.Usuario;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioRecord extends UpdatableRecordImpl<UsuarioRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = -859013766;

    /**
     * Setter for <code>ADMIN.USUARIO.USUARIO</code>.
     */
    public void setUsuario(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ADMIN.USUARIO.USUARIO</code>.
     */
    public String getUsuario() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ADMIN.USUARIO.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ADMIN.USUARIO.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ADMIN.USUARIO.NOMBRE</code>.
     */
    public void setNombre(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ADMIN.USUARIO.NOMBRE</code>.
     */
    public String getNombre() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ADMIN.USUARIO.RFC</code>.
     */
    public void setRfc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ADMIN.USUARIO.RFC</code>.
     */
    public String getRfc() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Usuario.USUARIO.USUARIO_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Usuario.USUARIO.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Usuario.USUARIO.NOMBRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Usuario.USUARIO.RFC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRfc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNombre();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRfc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value1(String value) {
        setUsuario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value2(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value3(String value) {
        setNombre(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord value4(String value) {
        setRfc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuarioRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioRecord
     */
    public UsuarioRecord() {
        super(Usuario.USUARIO);
    }

    /**
     * Create a detached, initialised UsuarioRecord
     */
    public UsuarioRecord(String usuario, String password, String nombre, String rfc) {
        super(Usuario.USUARIO);

        set(0, usuario);
        set(1, password);
        set(2, nombre);
        set(3, rfc);
    }
}
