/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.tables;


import SS.DesktopApp.Domain.Admin;
import SS.DesktopApp.Domain.Keys;
import SS.DesktopApp.Domain.Entities.ClaveproductoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Claveproducto extends TableImpl<ClaveproductoRecord> {

    private static final long serialVersionUID = 145075723;

    /**
     * The reference instance of <code>ADMIN.CLAVEPRODUCTO</code>
     */
    public static final Claveproducto CLAVEPRODUCTO = new Claveproducto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClaveproductoRecord> getRecordType() {
        return ClaveproductoRecord.class;
    }

    /**
     * The column <code>ADMIN.CLAVEPRODUCTO.CLAVEPROD</code>.
     */
    public final TableField<ClaveproductoRecord, String> CLAVEPROD = createField("CLAVEPROD", org.jooq.impl.SQLDataType.VARCHAR(8).nullable(false), this, "");

    /**
     * The column <code>ADMIN.CLAVEPRODUCTO.NOMBRE</code>.
     */
    public final TableField<ClaveproductoRecord, String> NOMBRE = createField("NOMBRE", org.jooq.impl.SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>ADMIN.CLAVEPRODUCTO.UNIDAD</code>.
     */
    public final TableField<ClaveproductoRecord, String> UNIDAD = createField("UNIDAD", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * Create a <code>ADMIN.CLAVEPRODUCTO</code> table reference
     */
    public Claveproducto() {
        this(DSL.name("CLAVEPRODUCTO"), null);
    }

    /**
     * Create an aliased <code>ADMIN.CLAVEPRODUCTO</code> table reference
     */
    public Claveproducto(String alias) {
        this(DSL.name(alias), CLAVEPRODUCTO);
    }

    /**
     * Create an aliased <code>ADMIN.CLAVEPRODUCTO</code> table reference
     */
    public Claveproducto(Name alias) {
        this(alias, CLAVEPRODUCTO);
    }

    private Claveproducto(Name alias, Table<ClaveproductoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Claveproducto(Name alias, Table<ClaveproductoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Claveproducto(Table<O> child, ForeignKey<O, ClaveproductoRecord> key) {
        super(child, key, CLAVEPRODUCTO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Admin.ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClaveproductoRecord> getPrimaryKey() {
        return Keys.SQL180711232201160;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClaveproductoRecord>> getKeys() {
        return Arrays.<UniqueKey<ClaveproductoRecord>>asList(Keys.SQL180711232201160);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ClaveproductoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClaveproductoRecord, ?>>asList(Keys.FK_CLAVEUNIDAD);
    }

    public Unidad unidad() {
        return new Unidad(this, Keys.FK_CLAVEUNIDAD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Claveproducto as(String alias) {
        return new Claveproducto(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Claveproducto as(Name alias) {
        return new Claveproducto(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Claveproducto rename(String name) {
        return new Claveproducto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Claveproducto rename(Name name) {
        return new Claveproducto(name, null);
    }
}
