/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.tables;


import SS.DesktopApp.Domain.Admin;
import SS.DesktopApp.Domain.Keys;
import SS.DesktopApp.Domain.Entities.ProductoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Producto extends TableImpl<ProductoRecord> {

    private static final long serialVersionUID = -1058392176;

    /**
     * The reference instance of <code>ADMIN.PRODUCTO</code>
     */
    public static final Producto PRODUCTO = new Producto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductoRecord> getRecordType() {
        return ProductoRecord.class;
    }

    /**
     * The column <code>ADMIN.PRODUCTO.CLAVE</code>.
     */
    public final TableField<ProductoRecord, String> CLAVE = createField("CLAVE", org.jooq.impl.SQLDataType.VARCHAR(12).nullable(false), this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.NOMBRE</code>.
     */
    public final TableField<ProductoRecord, String> NOMBRE = createField("NOMBRE", org.jooq.impl.SQLDataType.VARCHAR(84).nullable(false), this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.CLAVESAT</code>.
     */
    public final TableField<ProductoRecord, String> CLAVESAT = createField("CLAVESAT", org.jooq.impl.SQLDataType.VARCHAR(8).nullable(false), this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.PAQUETE</code>.
     */
    public final TableField<ProductoRecord, Integer> PAQUETE = createField("PAQUETE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.COSTO</code>.
     */
    public final TableField<ProductoRecord, Double> COSTO = createField("COSTO", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.PRECIO1</code>.
     */
    public final TableField<ProductoRecord, Double> PRECIO1 = createField("PRECIO1", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.PRECIO2</code>.
     */
    public final TableField<ProductoRecord, Double> PRECIO2 = createField("PRECIO2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.INVENTARIO</code>.
     */
    public final TableField<ProductoRecord, Boolean> INVENTARIO = createField("INVENTARIO", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.MINIMO</code>.
     */
    public final TableField<ProductoRecord, Integer> MINIMO = createField("MINIMO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ADMIN.PRODUCTO.ACTUAL</code>.
     */
    public final TableField<ProductoRecord, Integer> ACTUAL = createField("ACTUAL", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>ADMIN.PRODUCTO</code> table reference
     */
    public Producto() {
        this(DSL.name("PRODUCTO"), null);
    }

    /**
     * Create an aliased <code>ADMIN.PRODUCTO</code> table reference
     */
    public Producto(String alias) {
        this(DSL.name(alias), PRODUCTO);
    }

    /**
     * Create an aliased <code>ADMIN.PRODUCTO</code> table reference
     */
    public Producto(Name alias) {
        this(alias, PRODUCTO);
    }

    private Producto(Name alias, Table<ProductoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Producto(Name alias, Table<ProductoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Producto(Table<O> child, ForeignKey<O, ProductoRecord> key) {
        super(child, key, PRODUCTO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Admin.ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductoRecord> getPrimaryKey() {
        return Keys.SQL180711232200120;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductoRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductoRecord>>asList(Keys.SQL180711232200120);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProductoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProductoRecord, ?>>asList(Keys.FK_PRODCLAVE);
    }

    public Claveproducto claveproducto() {
        return new Claveproducto(this, Keys.FK_PRODCLAVE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Producto as(String alias) {
        return new Producto(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Producto as(Name alias) {
        return new Producto(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Producto rename(String name) {
        return new Producto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Producto rename(Name name) {
        return new Producto(name, null);
    }
}
