/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.tables;


import SS.DesktopApp.Domain.Admin;
import SS.DesktopApp.Domain.Keys;
import SS.DesktopApp.Domain.Entities.RenglonFacturaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RenglonFactura extends TableImpl<RenglonFacturaRecord> {

    private static final long serialVersionUID = -742767334;

    /**
     * The reference instance of <code>ADMIN.RENGLON_FACTURA</code>
     */
    public static final RenglonFactura RENGLON_FACTURA = new RenglonFactura();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RenglonFacturaRecord> getRecordType() {
        return RenglonFacturaRecord.class;
    }

    /**
     * The column <code>ADMIN.RENGLON_FACTURA.FACTURA</code>.
     */
    public final TableField<RenglonFacturaRecord, Integer> FACTURA = createField("FACTURA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ADMIN.RENGLON_FACTURA.ID_PROD</code>.
     */
    public final TableField<RenglonFacturaRecord, String> ID_PROD = createField("ID_PROD", org.jooq.impl.SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>ADMIN.RENGLON_FACTURA.PRECIO</code>.
     */
    public final TableField<RenglonFacturaRecord, Double> PRECIO = createField("PRECIO", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>ADMIN.RENGLON_FACTURA.CANTIDAD</code>.
     */
    public final TableField<RenglonFacturaRecord, Integer> CANTIDAD = createField("CANTIDAD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ADMIN.RENGLON_FACTURA.LISTA</code>.
     */
    public final TableField<RenglonFacturaRecord, Integer> LISTA = createField("LISTA", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ADMIN.RENGLON_FACTURA.SUBTOTAL</code>.
     */
    public final TableField<RenglonFacturaRecord, Double> SUBTOTAL = createField("SUBTOTAL", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>ADMIN.RENGLON_FACTURA</code> table reference
     */
    public RenglonFactura() {
        this(DSL.name("RENGLON_FACTURA"), null);
    }

    /**
     * Create an aliased <code>ADMIN.RENGLON_FACTURA</code> table reference
     */
    public RenglonFactura(String alias) {
        this(DSL.name(alias), RENGLON_FACTURA);
    }

    /**
     * Create an aliased <code>ADMIN.RENGLON_FACTURA</code> table reference
     */
    public RenglonFactura(Name alias) {
        this(alias, RENGLON_FACTURA);
    }

    private RenglonFactura(Name alias, Table<RenglonFacturaRecord> aliased) {
        this(alias, aliased, null);
    }

    private RenglonFactura(Name alias, Table<RenglonFacturaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RenglonFactura(Table<O> child, ForeignKey<O, RenglonFacturaRecord> key) {
        super(child, key, RENGLON_FACTURA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Admin.ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RenglonFacturaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RenglonFacturaRecord, ?>>asList(Keys.FK_RF, Keys.FK_RFPROD);
    }

    public Factura factura() {
        return new Factura(this, Keys.FK_RF);
    }

    public Producto producto() {
        return new Producto(this, Keys.FK_RFPROD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFactura as(String alias) {
        return new RenglonFactura(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RenglonFactura as(Name alias) {
        return new RenglonFactura(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RenglonFactura rename(String name) {
        return new RenglonFactura(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RenglonFactura rename(Name name) {
        return new RenglonFactura(name, null);
    }
}
