/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.tables;


import SS.DesktopApp.Domain.Admin;
import SS.DesktopApp.Domain.Keys;
import SS.DesktopApp.Domain.Entities.UnidadRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Unidad extends TableImpl<UnidadRecord> {

    private static final long serialVersionUID = -563417139;

    /**
     * The reference instance of <code>ADMIN.UNIDAD</code>
     */
    public static final Unidad UNIDAD = new Unidad();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UnidadRecord> getRecordType() {
        return UnidadRecord.class;
    }

    /**
     * The column <code>ADMIN.UNIDAD.CLAVEUNIDAD</code>.
     */
    public final TableField<UnidadRecord, String> CLAVEUNIDAD = createField("CLAVEUNIDAD", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>ADMIN.UNIDAD.NOMBRE</code>.
     */
    public final TableField<UnidadRecord, String> NOMBRE = createField("NOMBRE", org.jooq.impl.SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * Create a <code>ADMIN.UNIDAD</code> table reference
     */
    public Unidad() {
        this(DSL.name("UNIDAD"), null);
    }

    /**
     * Create an aliased <code>ADMIN.UNIDAD</code> table reference
     */
    public Unidad(String alias) {
        this(DSL.name(alias), UNIDAD);
    }

    /**
     * Create an aliased <code>ADMIN.UNIDAD</code> table reference
     */
    public Unidad(Name alias) {
        this(alias, UNIDAD);
    }

    private Unidad(Name alias, Table<UnidadRecord> aliased) {
        this(alias, aliased, null);
    }

    private Unidad(Name alias, Table<UnidadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Unidad(Table<O> child, ForeignKey<O, UnidadRecord> key) {
        super(child, key, UNIDAD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Admin.ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UnidadRecord> getPrimaryKey() {
        return Keys.SQL180711232202190;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UnidadRecord>> getKeys() {
        return Arrays.<UniqueKey<UnidadRecord>>asList(Keys.SQL180711232202190);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Unidad as(String alias) {
        return new Unidad(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Unidad as(Name alias) {
        return new Unidad(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Unidad rename(String name) {
        return new Unidad(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Unidad rename(Name name) {
        return new Unidad(name, null);
    }
}
