/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain.tables;


import SS.DesktopApp.Domain.Admin;
import SS.DesktopApp.Domain.Keys;
import SS.DesktopApp.Domain.Entities.UsuarioRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usuario extends TableImpl<UsuarioRecord> {

    private static final long serialVersionUID = 300633773;

    /**
     * The reference instance of <code>ADMIN.USUARIO</code>
     */
    public static final Usuario USUARIO = new Usuario();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsuarioRecord> getRecordType() {
        return UsuarioRecord.class;
    }

    /**
     * The column <code>ADMIN.USUARIO.USUARIO</code>.
     */
    public final TableField<UsuarioRecord, String> USUARIO_ = createField("USUARIO", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ADMIN.USUARIO.PASSWORD</code>.
     */
    public final TableField<UsuarioRecord, String> PASSWORD = createField("PASSWORD", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>ADMIN.USUARIO.NOMBRE</code>.
     */
    public final TableField<UsuarioRecord, String> NOMBRE = createField("NOMBRE", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>ADMIN.USUARIO.RFC</code>.
     */
    public final TableField<UsuarioRecord, String> RFC = createField("RFC", org.jooq.impl.SQLDataType.VARCHAR(13), this, "");

    /**
     * Create a <code>ADMIN.USUARIO</code> table reference
     */
    public Usuario() {
        this(DSL.name("USUARIO"), null);
    }

    /**
     * Create an aliased <code>ADMIN.USUARIO</code> table reference
     */
    public Usuario(String alias) {
        this(DSL.name(alias), USUARIO);
    }

    /**
     * Create an aliased <code>ADMIN.USUARIO</code> table reference
     */
    public Usuario(Name alias) {
        this(alias, USUARIO);
    }

    private Usuario(Name alias, Table<UsuarioRecord> aliased) {
        this(alias, aliased, null);
    }

    private Usuario(Name alias, Table<UsuarioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Usuario(Table<O> child, ForeignKey<O, UsuarioRecord> key) {
        super(child, key, USUARIO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Admin.ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsuarioRecord> getPrimaryKey() {
        return Keys.SQL180711232153460;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsuarioRecord>> getKeys() {
        return Arrays.<UniqueKey<UsuarioRecord>>asList(Keys.SQL180711232153460);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Usuario as(String alias) {
        return new Usuario(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Usuario as(Name alias) {
        return new Usuario(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Usuario rename(String name) {
        return new Usuario(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Usuario rename(Name name) {
        return new Usuario(name, null);
    }
}
