/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain;


import SS.DesktopApp.Domain.Entities.ClaveproductoRecord;
import SS.DesktopApp.Domain.Entities.ClienteRecord;
import SS.DesktopApp.Domain.Entities.FacturaRecord;
import SS.DesktopApp.Domain.Entities.PedidoRecord;
import SS.DesktopApp.Domain.Entities.ProductoRecord;
import SS.DesktopApp.Domain.Entities.RenglonFacturaRecord;
import SS.DesktopApp.Domain.Entities.RenglonRecord;
import SS.DesktopApp.Domain.Entities.UnidadRecord;
import SS.DesktopApp.Domain.Entities.UsuarioRecord;
import SS.DesktopApp.Domain.tables.Claveproducto;
import SS.DesktopApp.Domain.tables.Cliente;
import SS.DesktopApp.Domain.tables.Factura;
import SS.DesktopApp.Domain.tables.Pedido;
import SS.DesktopApp.Domain.tables.Producto;
import SS.DesktopApp.Domain.tables.Renglon;
import SS.DesktopApp.Domain.tables.RenglonFactura;
import SS.DesktopApp.Domain.tables.Unidad;
import SS.DesktopApp.Domain.tables.Usuario;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>ADMIN</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ClienteRecord, Integer> IDENTITY_CLIENTE = Identities0.IDENTITY_CLIENTE;
    public static final Identity<FacturaRecord, Integer> IDENTITY_FACTURA = Identities0.IDENTITY_FACTURA;
    public static final Identity<PedidoRecord, Integer> IDENTITY_PEDIDO = Identities0.IDENTITY_PEDIDO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClaveproductoRecord> SQL180711232201160 = UniqueKeys0.SQL180711232201160;
    public static final UniqueKey<ClienteRecord> SQL180711232154560 = UniqueKeys0.SQL180711232154560;
    public static final UniqueKey<FacturaRecord> SQL180711232156640 = UniqueKeys0.SQL180711232156640;
    public static final UniqueKey<PedidoRecord> SQL180711232155600 = UniqueKeys0.SQL180711232155600;
    public static final UniqueKey<ProductoRecord> SQL180711232200120 = UniqueKeys0.SQL180711232200120;
    public static final UniqueKey<UnidadRecord> SQL180711232202190 = UniqueKeys0.SQL180711232202190;
    public static final UniqueKey<UsuarioRecord> SQL180711232153460 = UniqueKeys0.SQL180711232153460;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ClaveproductoRecord, UnidadRecord> FK_CLAVEUNIDAD = ForeignKeys0.FK_CLAVEUNIDAD;
    public static final ForeignKey<FacturaRecord, ClienteRecord> FK_FC = ForeignKeys0.FK_FC;
    public static final ForeignKey<PedidoRecord, ClienteRecord> FK_PC = ForeignKeys0.FK_PC;
    public static final ForeignKey<ProductoRecord, ClaveproductoRecord> FK_PRODCLAVE = ForeignKeys0.FK_PRODCLAVE;
    public static final ForeignKey<RenglonRecord, PedidoRecord> FK_RP = ForeignKeys0.FK_RP;
    public static final ForeignKey<RenglonRecord, ProductoRecord> FK_RPROD = ForeignKeys0.FK_RPROD;
    public static final ForeignKey<RenglonFacturaRecord, FacturaRecord> FK_RF = ForeignKeys0.FK_RF;
    public static final ForeignKey<RenglonFacturaRecord, ProductoRecord> FK_RFPROD = ForeignKeys0.FK_RFPROD;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ClienteRecord, Integer> IDENTITY_CLIENTE = Internal.createIdentity(Cliente.CLIENTE, Cliente.CLIENTE.ID_CUS);
        public static Identity<FacturaRecord, Integer> IDENTITY_FACTURA = Internal.createIdentity(Factura.FACTURA, Factura.FACTURA.ID_FACTURA);
        public static Identity<PedidoRecord, Integer> IDENTITY_PEDIDO = Internal.createIdentity(Pedido.PEDIDO, Pedido.PEDIDO.ID_PEDIDO);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ClaveproductoRecord> SQL180711232201160 = Internal.createUniqueKey(Claveproducto.CLAVEPRODUCTO, "SQL180711232201160", Claveproducto.CLAVEPRODUCTO.CLAVEPROD);
        public static final UniqueKey<ClienteRecord> SQL180711232154560 = Internal.createUniqueKey(Cliente.CLIENTE, "SQL180711232154560", Cliente.CLIENTE.ID_CUS);
        public static final UniqueKey<FacturaRecord> SQL180711232156640 = Internal.createUniqueKey(Factura.FACTURA, "SQL180711232156640", Factura.FACTURA.ID_FACTURA);
        public static final UniqueKey<PedidoRecord> SQL180711232155600 = Internal.createUniqueKey(Pedido.PEDIDO, "SQL180711232155600", Pedido.PEDIDO.ID_PEDIDO);
        public static final UniqueKey<ProductoRecord> SQL180711232200120 = Internal.createUniqueKey(Producto.PRODUCTO, "SQL180711232200120", Producto.PRODUCTO.CLAVE);
        public static final UniqueKey<UnidadRecord> SQL180711232202190 = Internal.createUniqueKey(Unidad.UNIDAD, "SQL180711232202190", Unidad.UNIDAD.CLAVEUNIDAD);
        public static final UniqueKey<UsuarioRecord> SQL180711232153460 = Internal.createUniqueKey(Usuario.USUARIO, "SQL180711232153460", Usuario.USUARIO.USUARIO_);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ClaveproductoRecord, UnidadRecord> FK_CLAVEUNIDAD = Internal.createForeignKey(SS.DesktopApp.Domain.Keys.SQL180711232202190, Claveproducto.CLAVEPRODUCTO, "FK_CLAVEUNIDAD", Claveproducto.CLAVEPRODUCTO.UNIDAD);
        public static final ForeignKey<FacturaRecord, ClienteRecord> FK_FC = Internal.createForeignKey(SS.DesktopApp.Domain.Keys.SQL180711232154560, Factura.FACTURA, "FK_FC", Factura.FACTURA.CLIENTE);
        public static final ForeignKey<PedidoRecord, ClienteRecord> FK_PC = Internal.createForeignKey(SS.DesktopApp.Domain.Keys.SQL180711232154560, Pedido.PEDIDO, "FK_PC", Pedido.PEDIDO.CLIENTE);
        public static final ForeignKey<ProductoRecord, ClaveproductoRecord> FK_PRODCLAVE = Internal.createForeignKey(SS.DesktopApp.Domain.Keys.SQL180711232201160, Producto.PRODUCTO, "FK_PRODCLAVE", Producto.PRODUCTO.CLAVESAT);
        public static final ForeignKey<RenglonRecord, PedidoRecord> FK_RP = Internal.createForeignKey(SS.DesktopApp.Domain.Keys.SQL180711232155600, Renglon.RENGLON, "FK_RP", Renglon.RENGLON.PEDIDO);
        public static final ForeignKey<RenglonRecord, ProductoRecord> FK_RPROD = Internal.createForeignKey(SS.DesktopApp.Domain.Keys.SQL180711232200120, Renglon.RENGLON, "FK_RPROD", Renglon.RENGLON.ID_PROD);
        public static final ForeignKey<RenglonFacturaRecord, FacturaRecord> FK_RF = Internal.createForeignKey(SS.DesktopApp.Domain.Keys.SQL180711232156640, RenglonFactura.RENGLON_FACTURA, "FK_RF", RenglonFactura.RENGLON_FACTURA.FACTURA);
        public static final ForeignKey<RenglonFacturaRecord, ProductoRecord> FK_RFPROD = Internal.createForeignKey(SS.DesktopApp.Domain.Keys.SQL180711232200120, RenglonFactura.RENGLON_FACTURA, "FK_RFPROD", RenglonFactura.RENGLON_FACTURA.ID_PROD);
    }
}
