/*
 * This file is generated by jOOQ.
 */
package SS.DesktopApp.Domain;


import SS.DesktopApp.Domain.tables.Claveproducto;
import SS.DesktopApp.Domain.tables.Cliente;
import SS.DesktopApp.Domain.tables.Factura;
import SS.DesktopApp.Domain.tables.Pedido;
import SS.DesktopApp.Domain.tables.Producto;
import SS.DesktopApp.Domain.tables.Renglon;
import SS.DesktopApp.Domain.tables.RenglonFactura;
import SS.DesktopApp.Domain.tables.Unidad;
import SS.DesktopApp.Domain.tables.Usuario;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ADMIN
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ADMIN.CLAVEPRODUCTO</code>.
     */
    public static final Claveproducto CLAVEPRODUCTO = SS.DesktopApp.Domain.tables.Claveproducto.CLAVEPRODUCTO;

    /**
     * The table <code>ADMIN.CLIENTE</code>.
     */
    public static final Cliente CLIENTE = SS.DesktopApp.Domain.tables.Cliente.CLIENTE;

    /**
     * The table <code>ADMIN.FACTURA</code>.
     */
    public static final Factura FACTURA = SS.DesktopApp.Domain.tables.Factura.FACTURA;

    /**
     * The table <code>ADMIN.PEDIDO</code>.
     */
    public static final Pedido PEDIDO = SS.DesktopApp.Domain.tables.Pedido.PEDIDO;

    /**
     * The table <code>ADMIN.PRODUCTO</code>.
     */
    public static final Producto PRODUCTO = SS.DesktopApp.Domain.tables.Producto.PRODUCTO;

    /**
     * The table <code>ADMIN.RENGLON</code>.
     */
    public static final Renglon RENGLON = SS.DesktopApp.Domain.tables.Renglon.RENGLON;

    /**
     * The table <code>ADMIN.RENGLON_FACTURA</code>.
     */
    public static final RenglonFactura RENGLON_FACTURA = SS.DesktopApp.Domain.tables.RenglonFactura.RENGLON_FACTURA;

    /**
     * The table <code>ADMIN.UNIDAD</code>.
     */
    public static final Unidad UNIDAD = SS.DesktopApp.Domain.tables.Unidad.UNIDAD;

    /**
     * The table <code>ADMIN.USUARIO</code>.
     */
    public static final Usuario USUARIO = SS.DesktopApp.Domain.tables.Usuario.USUARIO;
}
